# Site settings
title: Intro to Everything
email: pittcsc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Everyone that has acheived greatness was once a beginner, and every beginner
  needs a starting place. Join us for the University of Pittsburgh first-ever
  Intro to Everything, where you can take the first steps toward learning about
  nearly anything you like.
baseurl: "/intro-to-everything/" # the subpath of your site, e.g. /blog/
url: "http://pittcsc.org" # the base hostname & protocol for your site
twitter_username: pittcsc
github_username:  Pitt-CSC

# Build settings
markdown: kramdown
sass:
  style: :compressed
